---
all:
  hosts:
    kb-vm:
      ansible_host: "{{ lookup('env', 'KB_VM_HOST') | default('kb-vm.home-engelhardt.uk') }}"
      ansible_user: deploy
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
